### ISSUE TITLE
Nunchuks deal 0 self-damage on miss

### ISSUE THREAD

**Issue by Awarets** [krakissi/endless-war#279]
https://github.com/krakissi/endless-war/blob/38b0794593ac023cede55db355d3bd29d0f1e5c7/ewcfg.py#L869

Not sure if this is intended behaviour or not, but by the time self damage is supposed to be applied to the attacking player, ctn.slimes_damage has already been set to 0, and so no self damage is dealt at all. I think this could be resolved by replacing the referenced line with:

    ctn.user_data.change_slimes(n = (-dmg / 2), source = source_self_damage)

**Comment by krakissi** [comment]
Feel free to make a pull request and I'll merge it.
