### ISSUE TITLE
!goto beach

### ISSUE THREAD

**Issue by forkes176** [krakissi/endless-war#281]
https://github.com/krakissi/endless-war/blob/9420ca1ccab51e6c079b84fe02aafc3f31fe0cea/ewcfg.py#L2884-L2891

Is this why my beautiful alias is broken?

**Comment by krakissi** [comment]
Looks broken. Probably "beach" and "assflats" get combined to "beachassflats." lol.

**Comment by krakissi** [comment]
https://github.com/krakissi/endless-war/commit/72173eb6a4fa04967f02c1b86df8a6a6b13398bb
